/** Auto-generated by scripts/generate-fa-icon-packs.ts - do not edit. */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const faUser = {
  prefix: "far",
  iconName: "user",
  icon: [
    448,
    512,
    [128100, 62144, 62470, "user-alt", "user-large"],
    "f007",
    "M144 128a80 80 0 1 1 160 0 80 80 0 1 1 -160 0zm208 0a128 128 0 1 0 -256 0 128 128 0 1 0 256 0zM48 480c0-70.7 57.3-128 128-128l96 0c70.7 0 128 57.3 128 128l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8c0-97.2-78.8-176-176-176l-96 0C78.8 304 0 382.8 0 480l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8z",
  ],
} as unknown as IconDefinition;
export const faUserAlt = {
  prefix: "far",
  iconName: "user",
  icon: [
    448,
    512,
    [128100, 62144, 62470, "user-alt", "user-large"],
    "f007",
    "M144 128a80 80 0 1 1 160 0 80 80 0 1 1 -160 0zm208 0a128 128 0 1 0 -256 0 128 128 0 1 0 256 0zM48 480c0-70.7 57.3-128 128-128l96 0c70.7 0 128 57.3 128 128l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8c0-97.2-78.8-176-176-176l-96 0C78.8 304 0 382.8 0 480l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8z",
  ],
} as unknown as IconDefinition;
export const faUserCircle = {
  prefix: "far",
  iconName: "circle-user",
  icon: [
    512,
    512,
    [62142, "user-circle"],
    "f2bd",
    "M406.5 399.6C387.4 352.9 341.5 320 288 320l-64 0c-53.5 0-99.4 32.9-118.5 79.6-35.6-37.3-57.5-87.9-57.5-143.6 0-114.9 93.1-208 208-208s208 93.1 208 208c0 55.7-21.9 106.2-57.5 143.6zm-40.1 32.7C334.4 452.4 296.6 464 256 464s-78.4-11.6-110.5-31.7c7.3-36.7 39.7-64.3 78.5-64.3l64 0c38.8 0 71.2 27.6 78.5 64.3zM256 512a256 256 0 1 0 0-512 256 256 0 1 0 0 512zm0-272a40 40 0 1 1 0-80 40 40 0 1 1 0 80zm-88-40a88 88 0 1 0 176 0 88 88 0 1 0 -176 0z",
  ],
} as unknown as IconDefinition;
export const faUserLarge = {
  prefix: "far",
  iconName: "user",
  icon: [
    448,
    512,
    [128100, 62144, 62470, "user-alt", "user-large"],
    "f007",
    "M144 128a80 80 0 1 1 160 0 80 80 0 1 1 -160 0zm208 0a128 128 0 1 0 -256 0 128 128 0 1 0 256 0zM48 480c0-70.7 57.3-128 128-128l96 0c70.7 0 128 57.3 128 128l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8c0-97.2-78.8-176-176-176l-96 0C78.8 304 0 382.8 0 480l0 8c0 13.3 10.7 24 24 24s24-10.7 24-24l0-8z",
  ],
} as unknown as IconDefinition;
