/** Auto-generated by scripts/generate-fa-icon-packs.ts - do not edit. */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const faWindowClose = {
  prefix: "far",
  iconName: "rectangle-xmark",
  icon: [
    512,
    512,
    [62164, "rectangle-times", "times-rectangle", "window-close"],
    "f410",
    "M64 112c-8.8 0-16 7.2-16 16l0 256c0 8.8 7.2 16 16 16l384 0c8.8 0 16-7.2 16-16l0-256c0-8.8-7.2-16-16-16L64 112zM0 128C0 92.7 28.7 64 64 64l384 0c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 448c-35.3 0-64-28.7-64-64L0 128zm334.1 49.9c9.4 9.4 9.4 24.6 0 33.9l-44.1 44.1 44.1 44.1c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-44.1-44.1-44.1 44.1c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l44.1-44.1-44.1-44.1c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l44.1 44.1 44.1-44.1c9.4-9.4 24.6-9.4 33.9 0z",
  ],
} as unknown as IconDefinition;
export const faWindowMaximize = {
  prefix: "far",
  iconName: "window-maximize",
  icon: [
    512,
    512,
    [128470],
    "f2d0",
    "M48 224l0 160c0 8.8 7.2 16 16 16l384 0c8.8 0 16-7.2 16-16l0-160-416 0zM0 128C0 92.7 28.7 64 64 64l384 0c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 448c-35.3 0-64-28.7-64-64L0 128z",
  ],
} as unknown as IconDefinition;
export const faWindowMinimize = {
  prefix: "far",
  iconName: "window-minimize",
  icon: [
    512,
    512,
    [128469],
    "f2d1",
    "M0 424c0-13.3 10.7-24 24-24l464 0c13.3 0 24 10.7 24 24s-10.7 24-24 24L24 448c-13.3 0-24-10.7-24-24z",
  ],
} as unknown as IconDefinition;
export const faWindowRestore = {
  prefix: "far",
  iconName: "window-restore",
  icon: [
    576,
    512,
    [],
    "f2d2",
    "M512 80L224 80c-8.8 0-16 7.2-16 16l0 16-48 0 0-16c0-35.3 28.7-64 64-64l288 0c35.3 0 64 28.7 64 64l0 192c0 35.3-28.7 64-64 64l-48 0 0-48 48 0c8.8 0 16-7.2 16-16l0-192c0-8.8-7.2-16-16-16zM368 288l-320 0 0 128c0 8.8 7.2 16 16 16l288 0c8.8 0 16-7.2 16-16l0-128zM64 160l288 0c35.3 0 64 28.7 64 64l0 192c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 224c0-35.3 28.7-64 64-64z",
  ],
} as unknown as IconDefinition;
