/** Auto-generated by scripts/generate-fa-icon-packs.ts - do not edit. */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const faZ = {
  prefix: "fas",
  iconName: "z",
  icon: [
    384,
    512,
    [122],
    "5a",
    "M0 64C0 46.3 14.3 32 32 32l320 0c12.4 0 23.7 7.2 29 18.4s3.6 24.5-4.4 34.1L100.3 416 352 416c17.7 0 32 14.3 32 32s-14.3 32-32 32L32 480c-12.4 0-23.7-7.2-29-18.4s-3.6-24.5 4.4-34.1L283.7 96 32 96C14.3 96 0 81.7 0 64z",
  ],
} as unknown as IconDefinition;
export const faZap = {
  prefix: "fas",
  iconName: "bolt",
  icon: [
    448,
    512,
    [9889, "zap"],
    "f0e7",
    "M338.8-9.9c11.9 8.6 16.3 24.2 10.9 37.8L271.3 224 416 224c13.5 0 25.5 8.4 30.1 21.1s.7 26.9-9.6 35.5l-288 240c-11.3 9.4-27.4 9.9-39.3 1.3s-16.3-24.2-10.9-37.8L176.7 288 32 288c-13.5 0-25.5-8.4-30.1-21.1s-.7-26.9 9.6-35.5l288-240c11.3-9.4 27.4-9.9 39.3-1.3z",
  ],
} as unknown as IconDefinition;
