export type UiCategory = {
  id: string;
  label: string;
  keywords: ReadonlyArray<string>;
};

export const UI_CATEGORIES: ReadonlyArray<UiCategory> = [
  { id: "accessibility", label: "Accessibility", keywords: ["access"] },
  {
    id: "alert",
    label: "Alert",
    keywords: ["alert", "triangle", "exclamation"],
  },
  { id: "alphabet", label: "Alphabet", keywords: ["alpha", "font", "letter"] },
  {
    id: "animals",
    label: "Animals",
    keywords: [
      "cat",
      "dog",
      "paw",
      "fish",
      "horse",
      "spider",
      "dove",
      "frog",
      "crow",
      "otter",
      "kiwi",
      "hippo",
    ],
  },
  {
    id: "arrows",
    label: "Arrows",
    keywords: ["arrow", "chevron", "caret", "turn", "rotate", "repeat", "shuffle", "sort"],
  },
  {
    id: "astronomy",
    label: "Astronomy",
    keywords: ["star", "moon", "sun", "planet", "meteor", "telescope", "satellite"],
  },
  {
    id: "automotive",
    label: "Automotive",
    keywords: ["car", "truck", "motor", "motorcycle", "gas", "tachometer", "road"],
  },
  {
    id: "buildings",
    label: "Buildings",
    keywords: [
      "building",
      "city",
      "house",
      "home",
      "warehouse",
      "school",
      "hospital",
      "church",
      "mosque",
      "synagogue",
    ],
  },
  {
    id: "business",
    label: "Business",
    keywords: [
      "briefcase",
      "chart",
      "trend",
      "analytics",
      "clipboard",
      "file-invoice",
      "handshake",
      "id-badge",
    ],
  },
  {
    id: "camping",
    label: "Camping",
    keywords: ["camp", "tent", "fire", "hiking", "mountain", "tree", "compass"],
  },
  {
    id: "charity",
    label: "Charity",
    keywords: ["hand-holding", "donate", "gift", "ribbon", "heart"],
  },
  {
    id: "charts-diagrams",
    label: "Charts + Diagrams",
    keywords: ["chart", "diagram", "project", "sitemap", "table", "bars", "pie", "line"],
  },
  {
    id: "childhood",
    label: "Childhood",
    keywords: ["child", "baby", "puzzle", "game", "toy", "school"],
  },
  {
    id: "clothing-fashion",
    label: "Clothing + Fashion",
    keywords: ["tshirt", "shirt", "hat", "shoe", "glasses", "ring", "gem"],
  },
  {
    id: "coding",
    label: "Coding",
    keywords: [
      "code",
      "bug",
      "terminal",
      "keyboard",
      "laptop",
      "server",
      "database",
      "git",
      "brackets",
    ],
  },
  {
    id: "communication",
    label: "Communication",
    keywords: ["comment", "message", "sms", "phone", "voicemail", "mail", "envelope", "inbox"],
  },
  {
    id: "connectivity",
    label: "Connectivity",
    keywords: ["wifi", "bluetooth", "signal", "rss", "ethernet", "network"],
  },
  {
    id: "construction",
    label: "Construction",
    keywords: ["hammer", "wrench", "tool", "hard-hat", "paint", "ruler", "trowel"],
  },
  {
    id: "design",
    label: "Design",
    keywords: ["palette", "pen", "pencil", "brush", "vector", "crop", "layer", "swatch"],
  },
  {
    id: "devices-hardware",
    label: "Devices + Hardware",
    keywords: [
      "mobile",
      "tablet",
      "desktop",
      "computer",
      "mouse",
      "keyboard",
      "camera",
      "print",
      "tv",
    ],
  },
  {
    id: "disaster-crisis",
    label: "Disaster + Crisis",
    keywords: ["virus", "biohazard", "radiation", "fire", "flood", "mask", "skull", "bomb"],
  },
  {
    id: "editing",
    label: "Editing",
    keywords: ["edit", "cut", "copy", "paste", "scissors", "eraser", "undo", "redo", "clone"],
  },
  {
    id: "education",
    label: "Education",
    keywords: ["book", "graduation", "school", "chalkboard", "apple", "atom"],
  },
  {
    id: "emoji",
    label: "Emoji",
    keywords: ["face", "smile", "laugh", "meh", "frown", "sad", "angry", "kiss", "surprise"],
  },
  {
    id: "energy",
    label: "Energy",
    keywords: ["bolt", "battery", "charging", "power", "plug", "solar", "wind"],
  },
  {
    id: "files",
    label: "Files",
    keywords: ["file", "folder", "save", "download", "upload", "archive"],
  },
  {
    id: "film-video",
    label: "Film + Video",
    keywords: ["film", "video", "camera", "clapper", "ticket", "tv"],
  },
  {
    id: "food-beverage",
    label: "Food + Beverage",
    keywords: ["coffee", "mug", "beer", "wine", "pizza", "burger", "utensils", "lemon", "apple"],
  },
  {
    id: "fruits-vegetables",
    label: "Fruits + Vegetables",
    keywords: ["apple", "carrot", "pepper", "lemon", "seedling"],
  },
  {
    id: "gaming",
    label: "Gaming",
    keywords: ["gamepad", "dice", "chess", "dragon", "dungeon", "trophy"],
  },
  {
    id: "genders",
    label: "Genders",
    keywords: ["gender", "mars", "venus", "transgender"],
  },
  {
    id: "halloween",
    label: "Halloween",
    keywords: ["ghost", "skull", "spider", "hat-wizard", "pumpkin"],
  },
  {
    id: "hands",
    label: "Hands",
    keywords: ["hand", "thumb", "clap", "point", "pray", "shake"],
  },
  {
    id: "holidays",
    label: "Holidays",
    keywords: ["gift", "holly", "candy-cane", "snowman", "menorah", "birthday"],
  },
  {
    id: "household",
    label: "Household",
    keywords: ["couch", "bed", "bath", "shower", "lightbulb", "key", "broom", "toilet"],
  },
  {
    id: "humanitarian",
    label: "Humanitarian",
    keywords: [
      "person",
      "people",
      "user",
      "users",
      "hand",
      "hands",
      "heart",
      "clinic",
      "hospital",
      "aid",
      "help",
      "support",
      "peace",
    ],
  },
  {
    id: "logistics",
    label: "Logistics",
    keywords: ["box", "boxes", "truck", "warehouse", "shipping", "dolly", "pallet"],
  },
  {
    id: "maps",
    label: "Maps",
    keywords: ["map", "location", "pin", "marker", "route", "compass", "globe"],
  },
  {
    id: "maritime",
    label: "Maritime",
    keywords: ["ship", "anchor", "water", "sailboat", "ferry"],
  },
  {
    id: "marketing",
    label: "Marketing",
    keywords: ["bullhorn", "ad", "campaign", "chart", "megaphone"],
  },
  {
    id: "mathematics",
    label: "Mathematics",
    keywords: ["square-root", "divide", "plus", "minus", "equals", "calculator", "infinity"],
  },
  {
    id: "media-playback",
    label: "Media Playback",
    keywords: ["play", "pause", "stop", "forward", "backward", "volume", "headphones"],
  },
  {
    id: "medical-health",
    label: "Medical + Health",
    keywords: [
      "heart",
      "clinic",
      "hospital",
      "stethoscope",
      "syringe",
      "pills",
      "virus",
      "x-ray",
      "mask",
    ],
  },
  {
    id: "money",
    label: "Money",
    keywords: ["dollar", "euro", "yen", "pound", "cash", "coins", "wallet", "credit-card"],
  },
  {
    id: "moving",
    label: "Moving",
    keywords: ["truck-moving", "box", "people-carry", "dolly", "route"],
  },
  {
    id: "music-audio",
    label: "Music + Audio",
    keywords: ["music", "note", "guitar", "drum", "microphone", "headphones"],
  },
  {
    id: "nature",
    label: "Nature",
    keywords: ["leaf", "tree", "seedling", "mountain", "water", "cloud", "sun"],
  },
  {
    id: "numbers",
    label: "Numbers",
    keywords: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
  },
  {
    id: "photos-images",
    label: "Photos + Images",
    keywords: ["image", "photo", "camera", "portrait", "frame"],
  },
  {
    id: "political",
    label: "Political",
    keywords: ["flag", "vote", "gavel", "landmark", "balance-scale"],
  },
  {
    id: "punctuation-symbols",
    label: "Punctuation + Symbols",
    keywords: ["question", "exclamation", "hashtag", "at", "asterisk", "percent"],
  },
  {
    id: "religion",
    label: "Religion",
    keywords: ["cross", "church", "mosque", "synagogue", "om", "pray", "star-of-david"],
  },
  {
    id: "science",
    label: "Science",
    keywords: ["atom", "flask", "microscope", "dna", "vial", "beaker"],
  },
  {
    id: "science-fiction",
    label: "Science Fiction",
    keywords: ["robot", "space", "meteor", "satellite", "ufo"],
  },
  {
    id: "security",
    label: "Security",
    keywords: ["lock", "unlock", "key", "shield", "fingerprint", "user-shield"],
  },
  {
    id: "shapes",
    label: "Shapes",
    keywords: ["circle", "square", "triangle", "hexagon", "star"],
  },
  {
    id: "shopping",
    label: "Shopping",
    keywords: ["cart", "bag", "store", "shop", "receipt", "barcode", "tag"],
  },
  {
    id: "social",
    label: "Social",
    keywords: ["share", "heart", "comment", "thumb", "users", "user-friends"],
  },
  {
    id: "spinners",
    label: "Spinners",
    keywords: ["spinner", "circle-notch", "sync", "rotate"],
  },
  {
    id: "sports-fitness",
    label: "Sports + Fitness",
    keywords: ["dumbbell", "running", "bicycle", "basketball", "football", "baseball", "medal"],
  },
  {
    id: "text-formatting",
    label: "Text Formatting",
    keywords: ["bold", "italic", "underline", "align", "list", "indent", "quote", "paragraph"],
  },
  {
    id: "time",
    label: "Time",
    keywords: ["clock", "hourglass", "stopwatch", "calendar", "bell"],
  },
  { id: "toggle", label: "Toggle", keywords: ["toggle", "switch"] },
  {
    id: "transportation",
    label: "Transportation",
    keywords: ["bus", "train", "subway", "plane", "car", "ship", "taxi"],
  },
  {
    id: "travel-hotel",
    label: "Travel + Hotel",
    keywords: ["suitcase", "plane", "passport", "hotel", "bed", "map", "globe"],
  },
  {
    id: "users-people",
    label: "Users + People",
    keywords: ["user", "users", "person", "people", "child", "male", "female"],
  },
  {
    id: "weather",
    label: "Weather",
    keywords: ["cloud", "sun", "rain", "snow", "bolt", "wind"],
  },
  {
    id: "writing",
    label: "Writing",
    keywords: ["pen", "pencil", "feather", "signature", "book", "note", "edit"],
  },
] as const;
